"""make user status non-nullable

Revision ID: 2bf9dee9424c
Revises: 86e9b2c36741
Create Date: 2025-08-04 00:40:46.710408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2bf9dee9424c'
down_revision: Union[str, Sequence[str], None] = '86e9b2c36741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        "UPDATE users SET status = 'ACTIVE' WHERE status IS NULL"
    )
    op.alter_column('users', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED', name='userstatus'),
               nullable=False,
               server_default=sa.text("'ACTIVE'")  # Set default to ACTIVE,
            )
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('bookings', 'status',
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    # op.alter_column('destinations', 'created_at',
    #            existing_type=postgresql.TIMESTAMP(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=False)
    # op.alter_column('destinations', 'updated_at',
    #            existing_type=postgresql.TIMESTAMP(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=False)
    # op.alter_column('itineraries', 'status',
    #            existing_type=sa.VARCHAR(),
    #            type_=postgresql.ENUM('DRAFT', 'GENERATED', 'BOOKED', 'CANCELLED', 'COMPLETED', name='itinerarystatus'),
    #            nullable=True)
    # op.alter_column('itineraries', 'updated_at',
    #            existing_type=postgresql.TIMESTAMP(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED', name='userstatus'),
               nullable=True, server_default=None)
    # op.alter_column('itineraries', 'updated_at',
    #            existing_type=sa.DateTime(timezone=True),
    #            type_=postgresql.TIMESTAMP(),
    #            existing_nullable=False)
    # op.alter_column('itineraries', 'status',
    #            existing_type=postgresql.ENUM('DRAFT', 'GENERATED', 'BOOKED', 'CANCELLED', 'COMPLETED', name='itinerarystatus'),
    #            type_=sa.VARCHAR(),
    #            nullable=False)
    # op.alter_column('destinations', 'updated_at',
    #            existing_type=sa.DateTime(timezone=True),
    #            type_=postgresql.TIMESTAMP(),
    #            existing_nullable=False)
    # op.alter_column('destinations', 'created_at',
    #            existing_type=sa.DateTime(timezone=True),
    #            type_=postgresql.TIMESTAMP(),
    #            existing_nullable=False)
    # op.alter_column('bookings', 'status',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # # ### end Alembic commands ###
