"""wire up auth & user-fk on itineraries

Revision ID: a94f2c8c2b97
Revises: 996a07b5bd58
Create Date: 2025-07-15 23:42:38.167355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a94f2c8c2b97'
down_revision: Union[str, Sequence[str], None] = '996a07b5bd58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
