services:
  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: traveldb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file:
      - ../.env
    volumes:
      - ../backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: